name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 4.2.1
homepage: https://jesway.com
repository: https://github.com/Jesway/flutter_translate

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: 2.2.2
  intl: 0.19.0
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: